FROM maven:3.3-jdk-8

COPY src bower.json pom.xml .bowerrc /usr/src/
RUN cd /usr/src \
 && mvn clean package

VOLUME "/dist"
CMD ["cp", "-rfv", "/usr/src/target/smeagol-app.jar", "/usr/src/src/main/webapp", "/usr/src/target/rubygems", "/dist/"]
