server:
  port: 8080
  contextPath: /smeagol

stage: development
homeDirectory: /tmp/smeagol

scm:
  url: https://192.168.56.2/scm

cas:
  url: https://192.168.56.2/cas
  serviceUrl: http://192.168.56.1:8080/smeagol